name: Build and Push Docker Image For Rem Discord Bot

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_LOGIN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./bot/rem
          push: true
          tags: ghcr.io/${{ github.repository }}/discord-bot-rem:latest
          secrets: |
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            OWNER_ID=${{ secrets.OWNER_ID }}
            WISE_API_TOKEN=${{ secrets.WISE_API_TOKEN }}
            PRIVATE_CHANNEL_ID=${{ secrets.PRIVATE_CHANNEL_ID }}
            GENERAL_CHANNEL_ID=${{ secrets.GENERAL_CHANNEL_ID }}
            LOG_CHANNEL_CATEGORY_ID=${{ secrets.LOG_CHANNEL_CATEGORY_ID }}
            LOG_CHANNEL_ID_BIRTHDAY=${{ secrets.LOG_CHANNEL_ID_BIRTHDAY }}
            LOG_CHANNEL_ID_EXCHANGE_RATE=${{ secrets.LOG_CHANNEL_ID_EXCHANGE_RATE }}

      - name: Verify image
        run: docker images
